let num1=9;


console.log(num1**(1/2)); // pegar raiz quadrada
console.log(num1**0.5); // pegar raiz quadrada
// let num2= Math.floor(num1); Arredonda o numero para baixo
// let num2= Math.ceil(num1); Arredonda para cima.
// let num2= Math.round(num1);  Arredonda para o mais proximo ex: 9.6 fica 10; 9.4 fica 9
//console.log(Math.max(1,2,8,6,2,47,6,47,626,5478)); Pega o maior valor dentro da sequencia
//console.log(Math.min(1,2,8,6,2,47,6,47,626,5478)); Pega o menor valor dentro da sequencia
//console.log(Math.random()*(10-5)+5; Pega um numero aleatorio entre 10 e 5 flutuante
//console.log(Math.floor(Math.random()*(10-5)+5); Pega um numero aleatorio entre 10 e 5 inteiro
// console.log(Math.PI); Valor de Pi
// console.log(Math.pow(2,10));// faz potencia
